[package]
name = "<package-name>"
version = "0.1.0"
authors = ["iknil <lk.nil@outlook.com>"]
description = "<description>"
license = "MIT/Apache-2.0"
repository = "https://github.com/iknil/wasm-modules"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
